class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article(
      {this.text,
      this.domain,
      this.by,
      this.age,
      this.score,
      this.commentsCount});
}

final articles = [
  new Article(
      text: "teSt1 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt2 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt3 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt4 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt5 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt6 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt7 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt8 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt9 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt10 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt11 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt12 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt13 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt14 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt15 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt16 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt17 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt18 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt19 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt20 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt21 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt22 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt23 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt24 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt25 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt26 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt27 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt28 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt29 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt30 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt31 text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
];
