class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article(
      {this.text,
      this.domain,
      this.by,
      this.age,
      this.score,
      this.commentsCount});
}

final articles = [
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
  new Article(
      text: "teSt text teSt text teSt text teSt text teSt text teSt text",
      domain: "google.com",
      by: "by teSt",
      age: "age teSt",
      score: 90,
      commentsCount: 13),
];
